# Generated by Django 5.2.1 on 2025-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigly_app', '0003_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='user',
            name='is_poster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
    ]
