# Generated by Django 5.2.1 on 2025-05-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigly_app', '0004_remove_user_is_buyer_remove_user_is_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_poster',
            new_name='is_buyer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_worker',
            new_name='is_seller',
        ),
    ]
