# Generated by Django 5.2.1 on 2025-06-03 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_chatgroup_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMessage',
            new_name='ChatMessage',
        ),
    ]
